// MongoDB IDs
// _id: 5a724953ab83547957541e6a
// Every ID takes 12 bytes
// From beginning to end:
// 4 bytes: timestamp
// 3 bytes: machine identifier
// 2 bytes: process identifier
// 3 bytes: counter

// 2 ^ 24 = 16 millions possible IDs
// IDs are generated by the MongoDB driver.
// Mongoose uses the MongoDB driver.
const mongoose = require('mongoose');
const id = new mongoose.Types.ObjectId();
console.log(id.getTimestamp());
const isValid = mongoose.Types.ObjectId
                    .isValid('1234');
console.log(isValid);